  version: "3.8"

  services:
    funnel-bot:
      container_name: funnel-easy-container
      build: .
      env_file: .env
      volumes:
        - ./:/app
      command: ["python", "app/main.py"]
      restart: always
